### ISSUE TITLE
PlayStation "wobble groove" protection replication

### ISSUE THREAD

**Issue by jan-kleks** [arduinocelentano/cdimage#12]
What a great project, thank you! It is amazing what you can do with a laser... You wrote on the project's Hackaday page that: "It might be possible to implement a copy protection algorithm". But would it be theoretically possible to recreate a physical copy protection with your method?

The PSX scene has been unsuccessfully trying for many years to create a disc which would boot on an unmodified console (for instance, to make a distribution of homebrew games much easier). It is a kind of a holy grail and an interesting technical challenge... This is what Coppeti writes about this protection scheme ([in their overview of the PS1 architecture](https://www.copetti.org/writings/consoles/playstation/))

>Like any other optical media, to fetch data from a CD, a laser beam is used to read the pits (zeroes) and lands (ones) from the track of the disc. Now, conventional discs are not 100% flat and they often have tiny fluctuations in their tracks. These defects are completely unnoticeable while reading the data since lasers can automatically calibrate themselves as they read.

>This is what Sony based their copy protection on: The Sub-CPU will allow reading discs whose Table of Contents (TOC) are engraved using a defined frequency informally known as Wobble Groove, which is only applied during mastering and cannot be replicated through conventional burners. The TOC is found in the inner section of the CD (called ‘Lead-In’ area) and instructs the laser on how to navigate throughout the disc, it’s repeated many times as a fault-tolerance mechanism.

See as well [a PSXDEV forum discussion thread](http://www.psxdev.net/forum/viewtopic.php?f=70&t=1266)

BTW, [a similar method has been used for PlayStation 2](https://techstomper.com/ps2-modding-a-history-of-playstation-piracy-part-ii/).

Regards

**Comment by david4599** [comment]
It won't work using this method. As said in the psxdev thread, the SCEx data is demodulated from the tracking error signal. This is not part of any CD image file at all. Even the burning softwares have no control of that.

On a PS1 disc, some parts of the data track are slightly oscillating at 22kHz (1x speed) in the lead-in area which will be read as tracking error. The presence of this 22kHz signal represents a one. No oscillation represents a zero.
But on a blank CD-R, this 22kHz signal is everywhere on it to encode the ATIP for disc information (in the lead-in) and writing timings for burning.
The PS1 wobble groove is made at the glass master creation step and cannot be replicated unless you ask to a CD pressing factory to do it which is expensive and they will probably deny your request.

Some people said this was possible with a normal burner by flashing custom firmware but I have no idea if this was actually done.
There is no documentation about that method on the internet.

Maybe, by burning intentional and controlled errors (non EFM data), it would be possible to trick the PS1 but this is purely theoretical and this involves heavy burner firmware modifications, really hard to do.
Moreover, since the only way would be to create errors, the PS1 drive may struggle to read the sectors and abort the boot process quickly.
