### ISSUE TITLE
CD-R?

### ISSUE THREAD

**Issue by anfractuosity** [arduinocelentano/cdimage#2]
Hi, first of all this is an awesome idea/project! 

Just wondering does this only work for CD-RW discs rather than CD-R?

I gave a quick try on a CD-R but couldn't notice a pattern.  So I've ordered some TDK 4-12X 700MB
discs for which there seems to be a preset.

I burned the CD-R using wodim, using something like:

```
wodim dev=/dev/sr0 -audio /tmp/track0
```

**Comment by arduinocelentano** [comment]
Hello.
Thank you for your interest.
Technically it should work for CD-R. The problem is that you should know (or rather guess) its data spiral geometry parameters. They are called "1st track length" and "Track delta" in the dialog. Well, maybe they should be renamed to "1st circle length" and "Circle delta" not to de confused with audio track.
So you'll probably spoil a lot of CD-R discs before you get some results. Moreover, all your test discs should be perfectly identical. Sometimes discs of the same model happen to have different parameters. Don't know why. After all, manufacturers have never cared since those discs were never supposed to be used this way. That is the only reason I used CD-RW.
However, if you manage to do it for certain type of CD-R, I think the picture would be sharper and more contrastive.

**Comment by anfractuosity** [comment]
Thanks a lot for the explanation!

Look forward to playing with this more when I get my CD-RWs.

**Comment by cliftbar** [comment]
In case anyone else ends up trying to do CD-R, here's the results of the 50 discs I burned through.  I used the calibration program from CD-Paint.  No idea how accurate any of this is though, I saw some small patterns but not much other than that

Disc: Verbatim CD-R DataLifePlus Injet Printable (white) 52x 700MB/80MIN, P/N 94755

tr0: 22821.83407 - 22896.49556
dtr: 1.40167 - 1.37399

Band guesses in calibration program: 9-11, 1-17, 3-11, 4-25, 1-8, 4-17, 0-7, 22-32
